version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - php

  php:
    image: football/php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: football
      MYSQL_DATABASE: football

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 81:80
